#!/usr/bin/env python3

import argparse
import socket
from raft_python.kv_cache import KVCache
from raft_python.raft_node import RaftNode
from raft_python.socket_wrapper import SocketWrapper
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='run a key-value store')
    parser.add_argument('port', type=int, help="Port number to communicate")
    parser.add_argument('id', type=str, help="ID of this replica")
    parser.add_argument('others', metavar='others', type=str,
                        nargs='+', help="IDs of other replicas")
    args = parser.parse_args()
    socket: SocketWrapper = SocketWrapper(args.port)
    kv_cache: KVCache = KVCache()
    raft_node = RaftNode(socket, kv_cache, args.id, args.others)
    raft_node.send_hello()
    raft_node.run()
